version: '3.9'
services:
  mysql:
    image: mysql
    container_name: mysql
    healthcheck:
      # ping이 정상 적으로 반환되는 것을 정상 작동의 기준으로 지정한다.
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 1s
      timeout: 1s
      retries: 30
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: mwohaji
      MYSQL_USER: mwohaji-server
      MYSQL_PASSWORD: 1234
      
  server:
    container_name: server
    build: 
      dockerfile: server/Dockerfile
    depends_on:
      firebase:
        condition: service_started
      mysql:
        condition: service_healthy
    ports:
      - 4000:4000
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mysql://mwohaji-server:1234@mysql/mwohaji
      - PORT=4000
      - GOOGLE_CLOUD_PROJECT=mwohaji-c8a10
      - FIREBASE_AUTH_EMULATOR_HOST=firebase:9099
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        set -ex
        sleep 10s # healthcheck를 해도 타이밍 이슈가 있어서 10초 정도 무조건 기다린다.
        yarn prisma:initdb
        yarn start

  firebase:
    image: andreysenov/firebase-tools
    container_name: firebase
    volumes:
      - ./.firebaserc:/home/node/.firebaserc
      - ./firebase.json:/home/node/firebase.json
    ports:
      - 4001:4001 # emulator ui
      - 9099:9099 # auth
    command: ["firebase", "emulators:start", "--only", "auth"]
