services:
  mysql:
    image: mysql:8
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: mwohaji
      MYSQL_USER: mwohaji-server
      MYSQL_PASSWORD: 1234
