version: '3.9'
services:
  mysql:
    image: mysql
    container_name: mysql
    healthcheck:
      # ping이 정상 적으로 반환되는 것을 정상 작동의 기준으로 지정한다.
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 1s
      timeout: 1s
      retries: 30
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1 # 1 = true
      MYSQL_DATABASE: mwohaji
      MYSQL_USER: mwohaji-server
      MYSQL_PASSWORD: 1234
      
  server:
    container_name: server
    build: 
      dockerfile: server/Dockerfile
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - 4000:4000
    environment:
      - DATABASE_URL=mysql://mwohaji-server:1234@mysql/mwohaji
      - PORT=4000
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        set -ex
        sleep 10s # healthcheck를 해도 타이밍 이슈가 있어서 10초 정도 무조건 기다린다.
        yarn prisma:initdb
        yarn start

