version: '3.9'
services:
  mysql:
    image: mysql
    ports:
      - 13306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: mwohaji
      MYSQL_USER: mwohaji-server
      MYSQL_PASSWORD: 1234

  firebase:
    image: andreysenov/firebase-tools
    volumes:
      - ../.firebaserc:/home/node/.firebaserc
      - ../firebase.json:/home/node/firebase.json
    ports:
      - 14001:4001 # emulator ui
      - 19099:9099 # auth
    command: ["firebase", "emulators:start", "--only", "auth"]
