name: CI App

on:
  push:
    branches: [main]
  pull_request:
    types: [synchronize, opened]
    paths:
      - "*"
      - ".github/workflows/ci-app.yaml"
      - "app/**"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: app/yarn.lock
      #  TRPC를 쓰다보니 서버쪽 디펜던시가 필요함
      - name: Install server dependeinces
        run: |
          cd sever
          yarn install --immutable
          cd .. 
        
      - name: Install dependencies
        run: |
          cd app
          yarn install --immutable
        
      - name: Run lint
        run: yarn lint:ci

      - name: Run test
        run: yarn test
