name: CI App

on:
  push:
    branches: [main]
  pull_request:
    types: [synchronize, opened]
    paths:
      - "*"
      - ".github/workflows/ci-app.yaml"
      - "app/**"

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
        
      - name: Install dependencies
        run: pnpm install
        
      - name: Run lint
        run: pnpm lint:ci
