name: CI Server Release

on:
  push:
    branches: [main]

env:
  DOCKER_TAG_PREFIX: mwohaji-c8a10/mwohaji-api

jobs:
  push_to_gcr:
    runs-on: ubuntu-latest
    steps:
    - uses: 'actions/checkout@v3'

    - id: 'auth'
      name: Authenticate to Google Cloud
      uses: 'google-github-actions/auth@v1'
      with:
        token_format: 'access_token'
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - uses: 'docker/login-action@v1'
      with:
        registry: 'asia-northeast3-docker.pkg.dev'
        username: 'oauth2accesstoken'
        password: '${{ steps.auth.outputs.access_token }}'

    - name: Build image
      run: docker build -f server/Dockerfile -t $DOCKER_TAG_PREFIX:$GITHUB_SHA .

    - name: push
      run: docker push $DOCKER_TAG_PREFIX:$GITHUB_SHA
