name: CI Server

on:
  push:
    branches: [main]
  pull_request:
    types: [synchronize, opened]
    paths:
      - "*"
      - ".github/workflows/ci-app.yaml"
      - "server/**"

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: server/yarn.lock

      - name: Install dependencies
        run: yarn install --immutable
        
      - name: Run lint
        run: yarn lint:ci

      - name: Setup test
        run: cd .. && docker compose version && docker compose up -d

      - name: Run test
        run: sleep 20s && yarn test # docker container가 완전히 켜질때 까지 기다립니다.
