name: CI Server

on:
  push:
    branches: [main]
  pull_request:
    types: [synchronize, opened]
    paths:
      - "*"
      - ".github/workflows/ci-app.yaml"
      - "server/**"

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: server/yarn.lock

      - name: Install dependencies
        run: yarn install --immutable
        
      - name: Run lint
        run: yarn lint:ci
      # 테스트에서 사용할 mysql을 셋업해줍니다.
      - uses: mirromutth/mysql-action@v1.1
        with:
          mysql database: 'mwohaji'
          mysql user: 'mwohaji-server'
          mysql password: '1234'

      - name: Run test
        run: sleep 20s && yarn test # mysql이 완전히 켜질때 까지 기다립니다.
